name: rankings_repository
description: A repository to manage rankings.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  dart_mappable: ^4.6.1
  firebase_ai: ^3.4.0

dev_dependencies:
  build_runner: ^2.10.2
  dart_mappable_builder: ^4.6.0
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^10.0.0
